spring:
  datasource:
    url: jdbc:h2:mem:testdb;TIME ZONE=Asia/Seoul
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    com.kimhchul.webapp: DEBUG
